name: Pre-Release
on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_draft:
    name: Create the release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⤵️　Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: 📝　Draft release
        uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true

      - name: 🔄　Update version in 'VERSION' and 'manifest.json' and push changes
        env:
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
          GITHUB_REPO: ${{ github.event.repository.name }}
        run: |
          echo "** Manifest before replace **"
          cat custom_components/$GITHUB_REPO/manifest.json
          sed -i 's/"version": ".*"/"version": "'$tag_name'"/g' custom_components/$GITHUB_REPO/manifest.json
          echo "** Manifest after replace **"
          cat custom_components/$GITHUB_REPO/manifest.json
          echo $tag_name > VERSION

      - name: 🚀　Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump version

      - name: 📝　Publish release
        uses: release-drafter/release-drafter@v5
        id: release_published
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          prerelease: true

      - name: "✏️　Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_PAT }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'

      - name: ✅　Commit release notes
        uses: EndBug/add-and-commit@v9
        with:
          message: Commit release notes
